name: sijilli
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.0
  flutter_svg: ^2.0.16
  hijri: ^3.0.0
  image_picker: ^1.2.0
  intl: ^0.20.1
  path: ^1.9.1
  pocketbase: ^0.23.0+1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/data/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_icon.png"
  min_sdk_android: 21
